language: objective-c
osx_image: xcode7.2

script:

- xcodebuild test -project ./Array2D/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./AVL\ Tree/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Binary\ Search/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Binary\ Search\ Tree/Solution\ 1/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Bloom\ Filter/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Breadth-First\ Search/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Heap/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Heap\ Sort/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Insertion\ Sort/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./K-Means/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Linked\ List/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Priority\ Queue/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Queue/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Quicksort/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Run-Length\ Encoding/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Select\ Minimum\ Maximum/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Selection\ Sort/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Shell\ Sort/Tests/Tests.xcodeproj -scheme Tests
- xcodebuild test -project ./Stack/Tests/Tests.xcodeproj -scheme Tests
